name: Build PowerToys

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest' # 或者指定版本，如 '16.0'
          
      - name: Print Environment Variables
        run: |
          echo $Env:VCTargetsPath

      - name: Install dependencies
        run: |
          nuget restore PowerToys.sln
          dotnet restore

      - name: Build PowerToys
        run: |
          dotnet build PowerToys.sln --configuration Release

      - name: Run tests
        run: |
          dotnet test PowerToys.sln --configuration Release
