name: Build PowerToys

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 0.86.0
          submodules: recursive

      - name: Setup build environment
        uses: ilammy/msvc-dev-cmd@v1
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'

      - name: Restore packages
        run: |
          # First restore C++ packages using NuGet
          nuget restore PowerToys.sln -MSBuildPath "$env:ProgramFiles\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin"
          
          # Then restore .NET packages
          dotnet restore PowerToys.sln

      - name: Build solution
        run: |
          msbuild PowerToys.sln /p:Configuration=Release /p:Platform="x64" /p:RestorePackagesConfig=true /p:UseSharedCompilation=false /m

      - name: Run tests
        run: |
          dotnet test PowerToys.sln --configuration Release --no-build
