name: Build PowerToys

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: |
          nuget restore PowerToys.sln
          dotnet restore

      - name: Build PowerToys
        run: |
          dotnet build PowerToys.sln --configuration Release

      - name: Run tests
        run: |
          dotnet test PowerToys.sln --configuration Release
